# Generated by Django 3.1.12 on 2026-02-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
